### PR TITLE
Update dipti-chhatrapati.yml

### PR DESCRIPTION
**Pull request by dips23**
Hi,

As suggested, I have updated the profile details, Please let me know if anything is further requiring to be updated.

Best,
Dipti Chhatrapati

### CODE REVIEW

**Comment by mkws121716** [comment]
Please also upload a .jpg image to the media folder titled dipti-chhatrapati.jpg using the instructions provided over email.

Change the naming convention of the image file in your .yml back to dipti-chhatrapati.jpg - not .png

**Comment by dips23** [comment]
Done - However, it seems that profile file (.yml) was re-created, so I have
updated the  details there with right  photo format.

Best Regards,

__________________________________________________________________

*Dipti Chhatrapati*

SharePoint – Office 365 Lead | Microsoft Practice

Mobile : 91-9167792306

   Email : dipti.chhatrapati@capgemini.com

  <https://www.linkedin.com/in/dipti-chhatrapati-33582b7/>
<https://twitter.com/dips84> [image: A screenshot of a cell phone
Description generated with high confidence]

*Respecting People and Technology is a top investment*

**Comment by mkws121716** [comment]
I do not see a PR for a photo and the naming convention of the photo in your .yml file still reads .png instead of .jpg

**Comment by dips23** [comment]
Hi MK,

Under dev branch, I see the history as below that says file has been
updated 5 days ago:

[image: image.png]

And the source file was updated as follows in the profile details:
[image: image.png]

[image: image.png]

Please suggest if I have missed any details/process.

Best Regards,
Dipti

**Comment by mkws121716** [comment]
I do not see any of that. I see that that file was created 29 days ago and no PRs have been committed. This is also incorrect because the image must be a .jpg, not a .png with the naming convention dipti-chhatrapati.jpg

[cid:image001.png@01D407C7.80A6AC00]

**Comment by dips23** [comment]
Hi MK,

at my end, it shows profile has been changed 6 days ago where I have
specified the jpg image
<https://github.com/dips23/rd-pr/blob/dev/rd/media/profiles/dipti-chhatrapati.jpg>
as suggested in profile
<https://github.com/dips23/rd-pr/blob/dev/rd/dipti-chhatrapati.yml>as well
as under media files - Can you please suggest what should we do in this
case ? Do I require to process anything from my side after committing the
changes ?

[image: image.png]


Best Regards,
Dipti Chhatrapati

**Pull request closed without merging**
