### PR TITLE
Update nicola-ferrini.yml

### PR DESCRIPTION
**Pull request by nicferr**
Tagline removed

### CODE REVIEW

**Comment by mkws121716** [comment]
You must add a tagline. They need to be technology-related interests separated by " / "

**Comment by huypub** [comment]
Could you please add a tagline, which need to be technology-related interests separated by " / "?Also please upload a picture.

**Comment by mksincero9** [comment]
This PR can be closed as this individual is no longer an RD and has been removed from the website.

**Comment by huypub** [comment]
Close the PR due to  this individual is no longer an RD

**Pull request closed without merging**
