### PR TITLE
Update christian-buckley.yml

### PR DESCRIPTION
**Pull request by buckleyplanet**

### CODE REVIEW

**Comment by mkws121716** [comment]
You should put your CEO title in the title line

**Comment by buckleyplanet** [comment]
Updated, and pull request submitted


----
cbuck@collabtalk.com<mailto:cbuck@collabtalk.com>

**Comment by mkws121716** [comment]
I meant that you should add your professional CEO title to the title line, not your MVP designation. Right now it appears as though you are solely affiliated with Microsoft which is misleading.

**Comment by buckleyplanet** [comment]
I did add both the MVP title and my company. Just re-submitted:

[cid:image001.png@01D3FBEB.813707B0]


----
cbuck@collabtalk.com<mailto:cbuck@collabtalk.com>

**Pull request merged**
