### PR TITLE
Update Colin Melia 2

### PR DESCRIPTION
**Pull request by colinizer**

### CODE REVIEW

**Comment by mkws121716** [comment]
There should be spaces between the tagline items and the /

**Comment by colinizer** [comment]
Updated

**Comment by colinizer** [comment]
Not sure what else needs to be done here

**Comment by huypub** [comment]
helped to remove the empty line at the end of file to resolve the validation error, then merged it to master branch.

**Comment by huypub** [comment]
The change in this PR is in live. Please review it from: https://rd.microsoft.com/en-us/

**Pull request merged**
